class Symbols:
    ANCHOR = "⚘"
    ARROW_LEFT = "«"
    ARROW_RIGHT = "»"
    BACK = "🔙 BACK"
    BULLET = "•"
    CHECK_MARK = "✔️"
    CLOSE = "🗑"
    CROSS_MARK = "✘"
    DIAMOND_1 = "◇"
    DIAMOND_2 = "◈"
    NEXT = "⤚ NEXT"
    PREVIOUS = "PREV ⤙"
    RADIO_SELECT = "◉"
    RADIO_UNSELECT = "〇"
    TRIANGLE_LEFT = "◂"
    TRIANGLE_RIGHT = "▸"